name: number_trivia
description: TDD Clean Architecture for Flutter

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Service locator
  get_it: ^2.0.1
  # BLoc state management
  flutter_bloc: ^0.21.0
  # Value equality
  equatable: ^0.4.0
  # Functional programming thingies
  dartz: ^0.8.6
  # Remote API
  data_connection_checker: ^0.3.4
  http: ^0.12.0+2
  # Local cache
  shared_preferences: ^0.5.3+4
  json_annotation: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.0
  flutter_launcher_icons: ^0.7.3
  build_runner: ^1.0.0
  json_serializable: ^2.0.0

flutter_icons:
  ios: true
  android: true
  image_path: "assets/logo/nt_logo.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/logo/